<?php
session_start();
require_once '../db.php';
// --- Include FPDF ---
$fpdf_path = __DIR__ . '/../fpdf/fpdf.php'; // Assumes fpdf is in the parent directory
if (file_exists($fpdf_path)) {
    require_once($fpdf_path); // Use require_once
} else {
    // Handle missing FPDF later
}


if (!isset($_SESSION['username'])) {
    header("Location: ../index.php");
    exit();
}

$username = $_SESSION['username'];
$role = $_SESSION['role'];

// --- Enhanced FPDF Class ---
class PDF extends FPDF {
    private $reportTitle = 'Report'; private $periodLabel = ''; private $generatedBy = '';
    private $colorAccent = [216, 76, 115]; private $colorLightPink = [255, 240, 246]; private $colorMuted = [107, 74, 87]; private $colorDark = [61, 26, 42]; private $colorBorder = [243, 208, 220];
    function setReportHeader($title, $period, $user) { $this->reportTitle = $title; $this->periodLabel = $period; $this->generatedBy = $user; }
    function Header() { $this->SetFillColor($this->colorAccent[0], $this->colorAccent[1], $this->colorAccent[2]); $this->Rect(0, 0, $this->GetPageWidth(), 25, 'F'); /* Adjusted Height */ $this->SetTextColor(255, 255, 255); $this->SetFont('Arial', 'B', 14); /* Adjusted Size */ $this->SetY(8); $this->Cell(0, 8, 'RCRAO Accounting - '.$this->reportTitle, 0, 1, 'C'); $this->SetFont('Arial', '', 10); $this->Cell(0, 6, $this->periodLabel, 0, 1, 'C'); $this->SetTextColor($this->colorDark[0], $this->colorDark[1], $this->colorDark[2]); $this->SetY(30); } // Adjusted Y
    function Footer() { $this->SetY(-15); $this->SetFont('Arial', 'I', 8); $this->SetTextColor(150); $this->Cell(0, 5, 'Generated By: ' . $this->generatedBy . ' on ' . date('Y-m-d H:i'), 0, 1, 'L'); $this->Cell(0, 5, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C'); }
    function BasicTable($header, $data) { $this->SetFillColor($this->colorAccent[0], $this->colorAccent[1], $this->colorAccent[2]); $this->SetTextColor(255); $this->SetDrawColor($this->colorAccent[0]-20 > 0 ? $this->colorAccent[0]-20 : 0, $this->colorAccent[1]-20 > 0 ? $this->colorAccent[1]-20 : 0, $this->colorAccent[2]-20 > 0 ? $this->colorAccent[2]-20 : 0); $this->SetLineWidth(.3); $this->SetFont('', 'B', 9); /* Smaller Header Font */ $widths = $this->CalculateWidths($header, $data); for ($i = 0; $i < count($header); $i++) $this->Cell($widths[$i], 7, $header[$i], 1, 0, 'C', true); /* Shorter Height */ $this->Ln(); $this->SetFont('Arial', '', 8); /* Smaller Data Font */ $this->SetTextColor($this->colorDark[0], $this->colorDark[1], $this->colorDark[2]); $this->SetFillColor(255); $this->SetDrawColor($this->colorBorder[0], $this->colorBorder[1], $this->colorBorder[2]); $fill = false;
        foreach ($data as $row) {
            $this->SetFillColor($fill ? 245 : 255);
            for ($i = 0; $i < count($header); $i++) {
                $cellValue = $row[$i] ?? '';
                // *** FIX: Apply iconv to cell content if it contains currency ***
                // Check if iconv function exists before calling
                if (function_exists('iconv') && mb_detect_encoding($cellValue, 'UTF-8', true) && strpos($cellValue, '₱') !== false) {
                    $cellValue = iconv('UTF-8', 'cp1252//IGNORE', $cellValue); // Use //IGNORE to skip invalid chars
                }
                $cleanValue = str_replace(['₱', ',', ' '], '', $cellValue); // Check original value for numeric alignment
                $align = (is_numeric($cleanValue)) ? 'R' : 'L';
                $this->Cell($widths[$i], 6, $cellValue, 'LR', 0, $align, true); /* Shorter Height */
            }
            $this->Ln();
            $fill = !$fill;
        }
        $this->Cell(array_sum($widths), 0, '', 'T'); $this->Ln(4);
    }
    function CalculateWidths($header, $data) { $num_cols = count($header); $pageWidth = $this->GetPageWidth() - 20; $widths = []; for ($i = 0; $i < $num_cols; $i++) { $widths[$i] = $this->GetStringWidth($header[$i]) + 6; } /* Reduced Padding */ $sampleData = array_slice($data, 0, 30); foreach ($sampleData as $row) { for ($i = 0; $i < $num_cols; $i++) { $cellValue = $row[$i] ?? ''; $widths[$i] = max($widths[$i], $this->GetStringWidth((string)$cellValue) + 6); } } $totalWidth = array_sum($widths); if ($totalWidth <= 0) { return array_fill(0, $num_cols, $pageWidth / $num_cols); } $scaleFactor = $pageWidth / $totalWidth; for ($i = 0; $i < $num_cols; $i++) { $widths[$i] *= $scaleFactor; } return $widths; }
    // Add iconv to SummarySection if used elsewhere, although not for this specific PDF action
    function SummarySection($title, $items) { /* ... same logic ... */
        foreach ($items as $label => $value) {
            // ... font setting ...
            $formattedValue = '₱ ' . number_format($value, 2);
            $labelConverted = function_exists('iconv') && mb_detect_encoding($label, 'UTF-8', true) ? iconv('UTF-8', 'cp1252//IGNORE', $label) : $label;
            $valueConverted = function_exists('iconv') && mb_detect_encoding($formattedValue, 'UTF-8', true) ? iconv('UTF-8', 'cp1252//IGNORE', $formattedValue) : $formattedValue;

        }
        // ... rest of function ...
    }
}
// --- END FPDF Class ---


// --- Handle POST actions ---
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';

    // --- PDF Generation Action ---
    if ($action === 'generate_current_view_pdf') {
        if (!file_exists($fpdf_path)) {
            die("FPDF library not found. Cannot generate PDF."); // Simple error for now
        }
        // No need to require again

        $jsonData = $_POST['pdf_data'] ?? '[]';
        $data = json_decode($jsonData, true); // Decode JSON into PHP array
        $filters = json_decode($_POST['pdf_filters'] ?? '{}', true); // Get filter info

        if (json_last_error() !== JSON_ERROR_NONE) {
             die("Error decoding PDF data.");
        }

        $pdf = new PDF('L', 'mm', 'A4'); // Use Landscape for wider table
        $pdf->AliasNbPages();

        // Build Title / Period Label
        $reportTitle = "Collections - Current View";
        $periodLabel = "Filters: ";
        $filterParts = [];
        if (!empty($filters['search'])) $filterParts[] = "Search='{$filters['search']}'";
        if (!empty($filters['pending'])) $filterParts[] = "Pending Only";
        if (empty($filterParts)) $filterParts[] = "None";
        $periodLabel .= implode(', ', $filterParts);
        $sortKeyLabel = str_replace(['_','only'], [' ',''], $filters['sortKey'] ?? 'Default'); // Make sort key readable
        $periodLabel .= " | Sorted By: " . ucwords($sortKeyLabel) . " " . ($filters['sortAsc'] ? '(Asc)' : '(Desc)');

        // *** FIX: Apply iconv to header labels if they contain special chars ***
        // Ensure iconv function exists before calling
        $titleConverted = function_exists('iconv') && mb_detect_encoding($reportTitle, 'UTF-8', true) ? iconv('UTF-8', 'cp1252//IGNORE', $reportTitle) : $reportTitle;
        $periodConverted = function_exists('iconv') && mb_detect_encoding($periodLabel, 'UTF-8', true) ? iconv('UTF-8', 'cp1252//IGNORE', $periodLabel) : $periodLabel;
        $userConverted = function_exists('iconv') && mb_detect_encoding($username, 'UTF-8', true) ? iconv('UTF-8', 'cp1252//IGNORE', $username) : $username;
        $pdf->setReportHeader($titleConverted, $periodConverted, $userConverted);

        $pdf->AddPage();
        $pdf->SetFont('Arial', '', 8);

        if (!empty($data)) {
            $header = ['Date', 'Client', 'Affiliation', 'Ref #', 'Amount', 'Received', 'Unpaid', 'Mode', 'In-Charge'];
            $table_data = [];
            $total_amount = 0; $total_received = 0; $total_unpaid = 0;

            foreach ($data as $row) {
                // Prepare data for the PDF table using display values from JS
                 // iconv fix is now handled within BasicTable method
                $rowData = [
                    $row['date'] ?? '',
                    $row['client'] ?? '',
                    $row['affiliation'] ?? '',
                    $row['ref'] ?? '',
                    $row['amount_display'] ?? '₱ 0.00', // Use display value
                    $row['received_display'] ?? '₱ 0.00',// Use display value
                    $row['unpaid_display'] ?? '₱ 0.00',  // Use display value
                    $row['mode'] ?? '',
                    $row['incharge'] ?? ''
                ];
                $table_data[] = $rowData;

                // Sum totals using raw numeric values from JS
                $total_amount += $row['amount'] ?? 0;
                $total_received += $row['received'] ?? 0;
                $total_unpaid += $row['unpaid'] ?? 0;
            }

            $pdf->BasicTable($header, $table_data);
            $pdf->Ln(5);
            $pdf->SetFont('Arial', 'B', 10);

            // *** FIX: Apply iconv to totals ***
            $totalAmountStr = 'Total Amount: ₱ ' . number_format($total_amount, 2);
            $totalReceivedStr = 'Total Cash Received: ₱ ' . number_format($total_received, 2);
            $totalUnpaidStr = 'Total Unpaid: ₱ ' . number_format($total_unpaid, 2);

            if (function_exists('iconv')) {
                $totalAmountStr = iconv('UTF-8', 'cp1252//IGNORE', $totalAmountStr);
                $totalReceivedStr = iconv('UTF-8', 'cp1252//IGNORE', $totalReceivedStr);
                $totalUnpaidStr = iconv('UTF-8', 'cp1252//IGNORE', $totalUnpaidStr);
            }

            $pdf->Cell(0, 6, $totalAmountStr, 0, 1, 'R');
            $pdf->Cell(0, 6, $totalReceivedStr, 0, 1, 'R');
            $pdf->Cell(0, 6, $totalUnpaidStr, 0, 1, 'R');

        } else {
            $pdf->SetFont('Arial', '', 10);
            $pdf->Cell(0, 10, 'No data matching the current view found.', 0, 1, 'C');
        }

        // --- Output PDF ---
        $filename = "Collections_CurrentView_" . date('Ymd_His') . ".pdf";
        if (ob_get_level()) { ob_end_clean(); } // Clean buffer
        $pdf->Output('D', $filename); // 'D' forces download
        exit(); // Stop script after PDF

    } // --- End PDF Generation Action ---

    elseif ($action === 'add') {
        if (empty($_POST['client_name']) || !isset($_POST['amount']) || !isset($_POST['cash_received'])) { header("Location: collections.php"); exit(); }
        $reference_number = "COLL-" . date("YmdHis") . "-" . rand(1000, 9999);
        $stmt = $conn->prepare("INSERT INTO collections (client_name, affiliation, reference_number, amount, cash_received, mode_of_payment, person_in_charge, created_at) VALUES (?,?,?,?,?,?,?,NOW())");
        if ($stmt) { $stmt->bind_param("sssddss", $_POST['client_name'], $_POST['affiliation'], $reference_number, $_POST['amount'], $_POST['cash_received'], $_POST['mode_of_payment'], $username); $stmt->execute(); $stmt->close(); }
    }
    elseif ($action === 'edit') {
        $id = intval($_POST['id']);
        if (empty($_POST['client_name']) || !isset($_POST['amount']) || !isset($_POST['cash_received']) || $id <= 0) { header("Location: collections.php"); exit(); }
        $stmt = $conn->prepare("UPDATE collections SET client_name=?, affiliation=?, amount=?, cash_received=?, mode_of_payment=? WHERE id=?");
        if ($stmt) { $stmt->bind_param("ssddsi", $_POST['client_name'], $_POST['affiliation'], $_POST['amount'], $_POST['cash_received'], $_POST['mode_of_payment'], $id); $stmt->execute(); $stmt->close(); }
    }
    elseif ($action === 'delete') {
        $id = intval($_POST['id']);
        if ($id > 0) { $conn->query("DELETE FROM collections WHERE id=$id"); }
    }

    // Redirect for standard actions (Add, Edit, Delete)
    header("Location: collections.php");
    exit();
}

// Fetch initial data for HTML table display
$collections_q = mysqli_query($conn, "SELECT *, (amount - IFNULL(cash_received,0)) AS unpaid_payment, DATE(created_at) as date_created_only FROM collections ORDER BY created_at DESC");
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Collections — RCRAO Accounting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <style>
    :root {
      --accent:#d84c73; --accent-light:#ffb6c1; --bg1:#fff0f6; --bg2:#ffe6ee; --card:#fff;
      --muted:#6b4a57; --shadow:0 8px 25px rgba(216,76,115,0.1);
      --sidebar-collapsed:72px; --sidebar-expanded:230px;
       --accent-dark: #b83b5e; /* Added */
    }
    *{box-sizing:border-box;font-family:"Poppins",sans-serif;margin:0;padding:0}
    body{background:linear-gradient(135deg,var(--bg1),var(--bg2));color:var(--muted);overflow-x:hidden}
    .sidebar{position:fixed;top:0;left:0;height:100vh;width:var(--sidebar-collapsed);background:linear-gradient(180deg,var(--accent) 0%,#ff7ea1 100%); display:flex;flex-direction:column;justify-content:space-between;padding:12px;transition:width .3s ease;z-index:1001}
    .sidebar:hover,.sidebar.expanded{width:var(--sidebar-expanded);box-shadow:var(--shadow)}
    nav.side-menu{margin-top:20px;display:flex;flex-direction:column;gap:8px}
    nav.side-menu a{display:flex;align-items:center;gap:15px;padding:12px;color:#fff;text-decoration:none;border-radius:8px;font-weight:500;transition: all .2s ease;}
    nav.side-menu a i{width:24px;text-align:center; font-size: 1.1em; transition: transform 0.2s ease;}
    nav.side-menu a .label{display:none; white-space: nowrap; opacity: 0; transition: opacity 0.2s ease;}
    .sidebar:hover nav.side-menu a .label,.sidebar.expanded nav.side-menu a .label{display:inline; opacity: 1;}
    nav.side-menu a:hover{background:rgba(255,255,255,0.2);transform:translateX(8px); }
    nav.side-menu a.active{background:rgba(255,255,255,0.15);}
    nav.side-menu a:hover i { transform: scale(1.1); }
    .main{margin-left:var(--sidebar-collapsed);padding:28px;transition: margin-left .3s ease;}
    .header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}
    .header h1{color:var(--accent-dark);font-size:24px;font-weight:700}
    .user-info{font-size:14px;font-weight:600;background:var(--card);padding:10px 14px;border-radius:10px;box-shadow:var(--shadow)}
    .toolbar{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:18px;background:var(--card);padding:14px 16px;border-radius:12px;box-shadow:var(--shadow)}
    .toolbar input{padding:8px 12px;border-radius:8px;border:1px solid #ccc;width:220px}

    /* Global Button Styles */
    .btn{ border: none; border-radius: 8px; padding: 10px 18px; font-weight: 600; cursor: pointer; transition: all 0.25s ease; background: var(--accent-light); color: var(--accent-dark); margin: 0 5px; font-family:"Poppins",sans-serif; font-size: 14px;}
    .btn:hover { background: var(--accent); color: #fff; transform: translateY(-2px); box-shadow: 0 4px 15px rgba(216,76,115,0.2);}
    .btn.primary{ background:var(--accent); color:#fff;}
    .btn.primary:hover{ background: var(--accent-dark); transform:translateY(-2px); box-shadow: 0 4px 15px rgba(216,76,115,0.3);}
    .btn.pending{background:#f5a3b0;color:#fff}
    .btn.pending:hover{background:#ff91a4}
    .btn.small{padding:8px 12px;font-size:13px}
    .btn i { margin-right: 8px; }

    .top-tabs{display:flex;gap:8px;margin-bottom:18px}
    .top-tabs .tab{background:var(--card);padding:10px 16px;border-radius:8px;cursor:pointer;font-weight:600;color:var(--muted);box-shadow:var(--shadow);transition:.2s}
    .top-tabs .tab.active{background:var(--accent);color:#fff}
    .table-card{background:var(--card);border-radius:14px;padding:16px;box-shadow:var(--shadow);overflow-x:auto}
    table{width:100%;border-collapse:collapse;text-align:left; font-size: 13px;}
    th,td{padding:10px 12px;border-bottom:1px solid #f3d0dc; white-space: nowrap;}
    th{background:#ffd6e5;color:#6b4a57;cursor:pointer;user-select:none;position:relative; font-weight: 600;}
    th .sort-icon{margin-left:6px;font-size:11px;color:#888}
    tr:hover{background:#fff6f9}
    .unpaid-row{background:#fff0f4; font-weight: 500;}
    .icon-btn{background:none;border:none;color:var(--accent);cursor:pointer;font-size:15px;margin:0 4px;transition:.2s}
    .icon-btn:hover{transform:scale(1.15); color: var(--accent-dark);}
    .pagination{text-align:center;margin-top:18px;display:flex;justify-content:center;gap:6px;flex-wrap:wrap}
    .pagination button{border:none;background:var(--accent);color:#fff;padding:6px 12px;border-radius:6px;cursor:pointer; font-size: 13px;}
    .pagination button.active{background:#ff91a4}

    /* Modal Styles */
    .modal { position: fixed; inset: 0; background: rgba(0, 0, 0, 0.5); display: none; justify-content: center; align-items: center; z-index: 1000; backdrop-filter: blur(5px); padding: 15px;}
    .modal.active { display: flex; animation: fadeIn .3s ease; }
    .modal-content { background: var(--card); border-radius: 16px; padding: 30px; width: 450px; max-width: 95%; box-shadow: 0 10px 40px rgba(0,0,0,0.15); animation: slideUp .35s ease; position: relative; }
    .modal h2 { color: var(--accent-dark); text-align: center; margin-bottom: 25px; font-weight: 700; font-size: 20px;}
    .modal form label { font-size: 14px; font-weight: 600; color: var(--muted); display: block; margin-top: 15px; margin-bottom: 5px; }
    .modal form input, .modal form select { width: 100%; padding: 12px 15px; margin-bottom: 12px; border: 1px solid #ddd; border-radius: 8px; background: #f9f9f9; font-size: 14px; transition: all 0.2s ease; font-family:"Poppins",sans-serif; }
    .modal form input:focus, .modal form select:focus { outline: none; border-color: var(--accent); background: #fff; box-shadow: 0 0 0 3px rgba(216, 76, 115, 0.15); }
    .modal .actions { display: flex; justify-content: flex-end; margin-top: 25px; gap: 10px; }
    @keyframes fadeIn { from { opacity: 0; transform: scale(0.95); } to { opacity: 1; transform: scale(1); } }
    @keyframes slideUp { from { transform: translateY(15px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
    </style>
</head>
<body>
<aside class="sidebar">
  <nav class="side-menu">
    <a href="../dashboard.php"><i class="fa fa-chart-pie"></i><span class="label">Dashboard</span></a>
    <a href="collections.php" class="active"><i class="fa fa-cash-register"></i><span class="label">Transactions</span></a>
    <?php if ($role === 'admin'): ?>
    <a href="../users.php"><i class="fa fa-users-cog"></i><span class="label">Users</span></a>
    <?php endif; ?>
    <a href="../logout.php"><i class="fa fa-sign-out-alt"></i><span class="label">Logout</span></a>
  </nav>
</aside>

<main class="main">
  <div class="header">
    <h1>Collections</h1>
    <div class="user-info">Logged in as: <b><?= htmlspecialchars($username) ?></b></div>
  </div>

  <div class="top-tabs">
    <div class="tab active">Collections</div>
    <div class="tab" onclick="location.href='receivables.php'">Receivables</div>
    <div class="tab" onclick="location.href='expenses.php'">Expenses</div>
  </div>

  <div class="toolbar">
    <input type="text" id="searchInput" placeholder="🔍 Search...">
    <button class="btn primary" id="openAddBtn"><i class="fa fa-plus"></i> New Collection</button>
    <button class="btn small" id="showPendingBtn"><i class="fa fa-clock"></i> Pending Only</button>
    <button class="btn small" id="generatePdfBtn" style="margin-left: 10px;"><i class="fa fa-file-pdf"></i> PDF Current View</button>
    <div style="margin-left:auto">
      <input type="number" id="rowsPerPageInput" placeholder="Rows / page" style="width:120px;padding:8px;border-radius:8px;border:1px solid #ddd" value="8" min="1">
    </div>
  </div>

  <div class="table-card">
    <table id="collectionsTable">
        <thead>
            <tr>
              <th data-key="date_created_only">Date <i class="fa fa-sort sort-icon"></i></th>
              <th data-key="client_name">Client <i class="fa fa-sort sort-icon"></i></th>
              <th data-key="affiliation">Affiliation <i class="fa fa-sort sort-icon"></i></th>
              <th data-key="reference_number">Ref # <i class="fa fa-sort sort-icon"></i></th>
              <th data-key="amount">Amount <i class="fa fa-sort sort-icon"></i></th>
              <th data-key="cash_received">Received <i class="fa fa-sort sort-icon"></i></th>
              <th data-key="unpaid_payment">Unpaid <i class="fa fa-sort sort-icon"></i></th>
              <th data-key="mode_of_payment">Mode <i class="fa fa-sort sort-icon"></i></th>
              <th data-key="person_in_charge">In-Charge <i class="fa fa-sort sort-icon"></i></th>
              <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php while ($r = mysqli_fetch_assoc($collections_q)):
              $unpaid = floatval($r['unpaid_payment']);
              unset($r['password']); // Safety
              $data = htmlentities(json_encode($r), ENT_QUOTES, 'UTF-8');
              $date_formatted = !empty($r['date_created_only']) ? date('M d, Y', strtotime($r['date_created_only'])) : '';
            ?>
            <tr class="<?= $unpaid > 0 ? 'unpaid-row' : '' ?>" data-row="<?= $data ?>">
              <td><?= $date_formatted ?></td>
              <td><?= htmlspecialchars($r['client_name']) ?></td>
              <td><?= htmlspecialchars($r['affiliation']) ?></td>
              <td><?= htmlspecialchars($r['reference_number']) ?></td>
              <td>₱<?= number_format($r['amount'], 2) ?></td>
              <td>₱<?= number_format($r['cash_received'], 2) ?></td>
              <td>₱<?= number_format($unpaid, 2) ?></td>
              <td><?= htmlspecialchars($r['mode_of_payment']) ?></td>
              <td><?= htmlspecialchars($r['person_in_charge']) ?></td>
              <td>
                <button class="icon-btn editBtn" title="Edit"><i class="fa fa-pen"></i></button>
                <button class="icon-btn deleteBtn" title="Delete"><i class="fa fa-trash"></i></button>
              </td>
            </tr>
            <?php endwhile; ?>
        </tbody>
    </table>
    <div class="pagination" id="pagination"></div>
  </div>
</main>

<div class="modal" id="modalAdd">
  <div class="modal-content">
    <h2 id="addTitle">Add Collection</h2>
    <form method="post" id="formAdd" action="collections.php">
      <input type="hidden" name="action" id="formAddAction" value="add">
      <input type="hidden" name="id" id="formAddId">
      <label>Client Name</label>
      <input type="text" name="client_name" id="client_name" required>
      <label>Affiliation</label>
      <input type="text" name="affiliation" id="affiliation" required>
      <label>Amount</label>
      <input type="number" step="0.01" name="amount" id="amount" required>
      <label>Cash Received</label>
      <input type="number" step="0.01" name="cash_received" id="cash_received" required>
      <label>Mode of Payment</label>
      <select name="mode_of_payment" id="mode_of_payment" required>
        <option value="Cash">Cash</option>
        <option value="Gcash">Gcash</option>
        <option value="Bank">Bank</option>
      </select>
      <div class="actions">
        <button type="button" class="btn" id="closeAdd">Cancel</button>
        <button type="submit" class="btn primary">Save</button>
      </div>
    </form>
  </div>
</div>

<form method="POST" action="collections.php" id="pdfForm" target="_blank" style="display: none;">
    <input type="hidden" name="action" value="generate_current_view_pdf">
    <input type="hidden" name="pdf_data" id="pdfDataInput">
    <input type="hidden" name="pdf_filters" id="pdfFiltersInput">
</form>

<script>
/* DOM helpers & initial state */
const searchInput = document.getElementById('searchInput');
const showPendingBtn = document.getElementById('showPendingBtn');
const rowsPerPageInput = document.getElementById('rowsPerPageInput');
const allRows = Array.from(document.querySelectorAll('#collectionsTable tbody tr'));
const generatePdfBtn = document.getElementById('generatePdfBtn');
const pdfForm = document.getElementById('pdfForm');
const pdfDataInput = document.getElementById('pdfDataInput');
const pdfFiltersInput = document.getElementById('pdfFiltersInput');


let showingPending = false;
let rowsPerPage = parseInt(rowsPerPageInput.value) || 8;
let currentPage = 1;
let currentSortKey = 'created_at'; // Default sort from PHP
let currentSortAsc = false; // Default DESC


/* Add / Edit modal wiring */
const modalAdd = document.getElementById('modalAdd');
const formAdd = document.getElementById('formAdd');
const openAddBtn = document.getElementById('openAddBtn');
const closeAdd = document.getElementById('closeAdd');
const addTitle = document.getElementById('addTitle');

openAddBtn.onclick = () => { /* ... */
  formAdd.reset();
  document.getElementById('formAddAction').value = 'add';
  document.getElementById('formAddId').value = '';
  addTitle.textContent = 'New Collection';
  modalAdd.classList.add('active');
};
closeAdd.onclick = () => modalAdd.classList.remove('active');

document.querySelectorAll('.editBtn').forEach(btn=>{ /* ... */
  btn.onclick = (e)=>{
    const tr = btn.closest('tr');
    const data = JSON.parse(tr.dataset.row);
    document.getElementById('formAddAction').value = 'edit';
    document.getElementById('formAddId').value = data.id;
    document.getElementById('client_name').value = data.client_name;
    document.getElementById('affiliation').value = data.affiliation || '';
    document.getElementById('amount').value = parseFloat(data.amount || 0).toFixed(2);
    document.getElementById('cash_received').value = parseFloat(data.cash_received || 0).toFixed(2);
    document.getElementById('mode_of_payment').value = data.mode_of_payment || 'Cash';
    addTitle.textContent = 'Edit Collection';
    modalAdd.classList.add('active');
  }
});

/* Delete - SweetAlert */
document.querySelectorAll('.deleteBtn').forEach(btn=>{ /* ... */
  btn.onclick = ()=>{
    const data = JSON.parse(btn.closest('tr').dataset.row);
    const id = data.id;
    Swal.fire({ title: 'Are you sure?', text: `Delete collection from ${data.client_name}?`, icon: 'warning', showCancelButton: true, confirmButtonText: 'Yes, delete it!', buttonsStyling: false, customClass: { confirmButton: 'btn primary', cancelButton: 'btn' }
    }).then((result) => {
        if (result.isConfirmed) {
            const fd = new FormData(); fd.append('action','delete'); fd.append('id', id);
            fetch('collections.php', { method:'POST', body: fd }).then(()=> location.reload());
        }
    });
  }
});

/* --- Filter, Sort, Pagination, PDF Generation --- */

function getFilteredRows() { /* ... same ... */
  const q = searchInput.value.toLowerCase().trim();
  return allRows.filter(r => {
    const textContent = r.textContent.toLowerCase(); const matchesSearch = !q || textContent.includes(q);
    if (!matchesSearch) return false;
    if (showingPending) { const data = JSON.parse(r.dataset.row); const unpaid = parseFloat(data.unpaid_payment || 0); return unpaid > 0; }
    return true;
  });
}

function sortRows(rowsToSort, key, asc) { /* ... same ... */
    rowsToSort.sort((a, b) => {
      const A = JSON.parse(a.dataset.row)[key]; const B = JSON.parse(b.dataset.row)[key];
      if (['amount', 'cash_received', 'unpaid_payment'].includes(key)) { const numA = parseFloat(A) || 0; const numB = parseFloat(B) || 0; return asc ? (numA - numB) : (numB - numA); }
       if (key === 'date_created_only') { const dateA = new Date(JSON.parse(a.dataset.row)['created_at'] || 0); const dateB = new Date(JSON.parse(b.dataset.row)['created_at'] || 0); return asc ? dateA - dateB : dateB - dateA; }
      const sa = (A || '').toString().toLowerCase(); const sb = (B || '').toString().toLowerCase(); return asc ? sa.localeCompare(sb) : sb.localeCompare(sa);
    });
}

function renderTable() { /* ... same ... */
    const filteredRows = getFilteredRows(); sortRows(filteredRows, currentSortKey, currentSortAsc);
    const tbody = document.querySelector('#collectionsTable tbody'); tbody.innerHTML = '';
    const start = (currentPage - 1) * rowsPerPage; const end = start + rowsPerPage; const pageRows = filteredRows.slice(start, end);
    pageRows.forEach(r => tbody.appendChild(r));
    renderPagination(filteredRows.length);
}

function renderPagination(totalFilteredRows) { /* ... same ... */
  const container = document.getElementById('pagination'); container.innerHTML = ''; const totalPages = Math.max(1, Math.ceil(totalFilteredRows / rowsPerPage));
  if (totalPages <= 1) return;
  for (let i = 1; i <= totalPages; i++) { const b = document.createElement('button'); b.textContent = i; if (i === currentPage) b.classList.add('active'); b.onclick = () => { currentPage = i; renderTable(); }; container.appendChild(b); }
}

/* --- Event Listeners --- */
searchInput.addEventListener('input', () => { currentPage = 1; renderTable(); });
showPendingBtn.onclick = () => { showingPending = !showingPending; showPendingBtn.innerHTML = showingPending ? '<i class="fa fa-list"></i> Show All' : '<i class="fa fa-clock"></i> Pending Only'; showPendingBtn.classList.toggle('pending', showingPending); currentPage = 1; renderTable(); };
rowsPerPageInput.addEventListener('change', () => { let newRows = parseInt(rowsPerPageInput.value); if (newRows > 0) { rowsPerPage = newRows; } else { rowsPerPageInput.value = rowsPerPage; } currentPage = 1; renderTable(); });
document.querySelectorAll('th[data-key]').forEach(th => { /* ... same sort listener ... */
  th.addEventListener('click', () => {
    const key = th.dataset.key; if (currentSortKey === key) { currentSortAsc = !currentSortAsc; } else { currentSortKey = key; currentSortAsc = true; }
    document.querySelectorAll('.sort-icon').forEach(i => i.className = 'fa fa-sort sort-icon'); th.querySelector('.sort-icon').className = currentSortAsc ? 'fa fa-sort-up sort-icon' : 'fa fa-sort-down sort-icon';
    currentPage = 1; renderTable();
  });
});

/* PDF Generation Button Listener */
generatePdfBtn.addEventListener('click', () => {
    const visibleRows = Array.from(document.querySelectorAll('#collectionsTable tbody tr'))
                                    .filter(row => row.style.display !== 'none'); // Get only visible rows

    const dataForPdf = visibleRows.map(row => {
        const rowData = JSON.parse(row.dataset.row);
        const cells = row.getElementsByTagName('td');
        return {
            date: cells[0]?.textContent || '', client: cells[1]?.textContent || '', affiliation: cells[2]?.textContent || '', ref: cells[3]?.textContent || '',
            amount_display: cells[4]?.textContent || '₱ 0.00', received_display: cells[5]?.textContent || '₱ 0.00', unpaid_display: cells[6]?.textContent || '₱ 0.00',
            mode: cells[7]?.textContent || '', incharge: cells[8]?.textContent || '',
            amount: parseFloat(rowData.amount || 0), received: parseFloat(rowData.cash_received || 0), unpaid: parseFloat(rowData.unpaid_payment || 0)
        };
    });
    const filtersForPdf = { search: searchInput.value, pending: showingPending, sortKey: currentSortKey, sortAsc: currentSortAsc };

    pdfDataInput.value = JSON.stringify(dataForPdf);
    pdfFiltersInput.value = JSON.stringify(filtersForPdf);
    pdfForm.submit();
});


/* --- Form Validation & Modal Close --- */
renderTable(); // Initial render

formAdd.addEventListener('submit', function(e){ /* ... same validation ... */
  const client = document.getElementById('client_name').value.trim(); const amount = parseFloat(document.getElementById('amount').value); const cash = parseFloat(document.getElementById('cash_received').value);
  if (!client || isNaN(amount) || amount <= 0 || isNaN(cash) || cash < 0) { e.preventDefault(); Swal.fire({ icon: 'error', title: 'Validation Error', text: 'Client name, valid amount (>0), and cash received (>=0) required.', buttonsStyling: false, customClass: { confirmButton: 'btn primary' } }); return false; }
  if (cash > amount) { e.preventDefault(); Swal.fire({ icon: 'warning', title: 'Validation Error', text: 'Cash received cannot be greater than amount.', buttonsStyling: false, customClass: { confirmButton: 'btn primary' } }); return false; }
});
document.querySelectorAll('.modal').forEach(m=>{ /* ... same close logic ... */
  m.addEventListener('click', (ev)=>{ if (ev.target === m) m.classList.remove('active'); });
});
</script>
</body>
</html>